# Using Pipenv
FROM python:3.8

# Set ENV
ENV FLASK_APP=sub_app.py

# Create workspace ./app
WORKDIR /app/sub

# Copy pip files
COPY ./Pipfile* ./

# install dependencies
RUN pip install --upgrade pip && \
  pip install pipenv && \
  pipenv install --dev --system --deploy --ignore-pipfile

# copy the rest of files over
COPY . ./

# # "--host=0.0.0.0" - sets docker to run on local host
CMD flask run --host=0.0.0.0 --port=5001
